version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_DATABASE=biblioteca
      - MYSQL_ROOT_PASSWORD=''
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - employee-mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

  web_libros:
    build: .
    container_name: web_libros
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/web_libros
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    volumes:
      - .:/app
    networks:
      - employee-mysql

volumes:
  mysql_data:

networks:
  employee-mysql:
    driver: bridge
